name: prato_limpo
description: Prato Limpo — Entenda o que você come
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  google_generative_ai: ^0.4.3
  google_mlkit_text_recognition: ^0.11.0
  speech_to_text: ^6.6.1
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  flutter_widget_from_html_core: ^0.14.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  intl: ^0.20.2
  collection: ^1.18.0

  # Flutter localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/demo/

